services:

  backend:
    build: ./backend/
    ports:
      - 8000:8000
    command: /bin/sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
  
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    command: /bin/sh -c "npm start"